DROP SCHEMA PUBLIC CASCADE;

CREATE SCHEMA IF NOT EXISTS tautdb AUTHORIZATION DBA; 
-- MySQL dump 10.13  Distrib 8.0.17, for Win64 (x86_64)
--
-- Host: tautdb.c6y6bex5zmy8.us-east-2.rds.amazonaws.com    Database: tautdb
-- ------------------------------------------------------
-- Server version	5.7.22-log

--
-- Table structure for table `group_members`
--

DROP TABLE IF EXISTS tautdb.group_members;
CREATE TABLE tautdb.group_members (
  group_name varchar(255) NOT NULL,
  username varchar(255) NOT NULL,
  PRIMARY KEY (group_name, username)
);

--
-- Table structure for table `groups`
--

DROP TABLE IF EXISTS tautdb.groups;

CREATE TABLE tautdb.groups (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  is_active boolean NOT NULL,
  group_name varchar(255) NOT NULL UNIQUE,
  primary_moderator varchar(255) NOT NULL,
  PRIMARY KEY (id)
);
--
-- Table structure for table `member_aliases`
--
DROP TABLE IF EXISTS tautdb.member_aliases;


CREATE TABLE tautdb.member_aliases (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  username varchar(255) NOT NULL,
  group_name varchar(255) NOT NULL,
  alias varchar(45) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

--
-- Table structure for table `messages`
--
DROP TABLE IF EXISTS tautdb.messages;

CREATE TABLE tautdb.messages (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  content varchar(1000) NOT NULL,
  sender_username varchar(255) NOT NULL,
  recipient_username varchar(255) NOT NULL,
  date_sent TIMESTAMP NOT NULL,
  type varchar(255) DEFAULT NULL,
  content_type varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

--
-- Table structure for table `moderators`
--

DROP TABLE IF EXISTS tautdb.moderators;

CREATE TABLE tautdb.moderators (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  group_name varchar(255) NOT NULL,
  username varchar(45) NOT NULL,
  PRIMARY KEY (id)
);

--
-- Table structure for table `subgroups`
--
DROP TABLE IF EXISTS tautdb.subgroups;

CREATE TABLE tautdb.subgroups (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  subgroup_name varchar(255) NOT NULL,
  parent_group_name varchar(255) NOT NULL,
  PRIMARY KEY (id)
);

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS tautdb.users;

CREATE TABLE tautdb.users (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  name varchar(255) NOT NULL UNIQUE,
  status varchar(45) DEFAULT NULL,
  is_bot boolean NOT NULL,
  searchable boolean NOT NULL,
  PRIMARY KEY (id)
);

-- Dump completed on 2019-12-01 21:16:49
